version: '3.8'

services:
  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
    env_file:
      - .env
    networks:
      - my_network

  portainer:
    image: portainer/portainer-ce:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    environment:
      # This is the official and correct way to set the base URL for Portainer
      - PUBLIC_URL=/portainer
    networks:
      - my_network

networks:
  my_network:
    external: false

volumes:
  caddy_data: {}
  portainer_data: {}
