version: '3.8'

services:
  portainer:
    image: portainer/portainer-ce:latest
    restart: unless-stopped
    command: --http-disabled
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - caddy_net
    environment:
      - PORTAINER_HTTP_DISABLED=true

  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - DOMAIN=${DOMAIN}
    networks:
      - caddy_net

volumes:
  portainer_data:
  caddy_data:
  caddy_config:

networks:
  caddy_net:
