version: '3.8'

services:
  portainer:
    image: portainer/portainer-ce:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    environment:
      - VIRTUAL_HOST=${DOMAIN}
      - VIRTUAL_PATH=/portainer
    networks:
      - caddy_net

  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - DOMAIN=${DOMAIN}
    networks:
      - caddy_net
    command: [
      "caddy", "reverse-proxy",
      "--from", "${DOMAIN}",
      "--to", "portainer:9000",
      "--change-host-header",
      "--internal-certs"
    ]

volumes:
  portainer_data:
  caddy_data:
  caddy_config:

networks:
  caddy_net:
