version: '3.8'

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - portainer_data:/data
    networks:
      - proxy
    environment:
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
    # Add this command to set the base URL
    command: --admin-password=${ADMIN_PASSWORD:-admin} --hide-label=owner --logo="https://portainer.io/img/logo.svg" --base-url=/portainer
    expose:
      - 9000

  caddy:
    # Rest of your caddy configuration remains the same
    # ...
