version: '3.8'

services:
  portainer:
    image: portainer/portainer-ce:latest
    restart: unless-stopped
    command: -H unix:///var/run/docker.sock
    volumes:
      - ${DOCKER_HOST}:/var/run/docker.sock
      - ./data:/data
    networks:
      - portainer-network

  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./caddy_data:/data
      - ./caddy_config:/config
    networks:
      - portainer-network

networks:
  portainer-network:
    driver: bridge
