version: '3.8'

services:
  portainer:
    image: portainer/portainer-ce:latest
    restart: unless-stopped
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - portainer-network
    labels:
      caddy.reverse_proxy: "portainer:9000"
      caddy.rewrite: "/portainer{path} /{path}"
      caddy.handle_path: "/portainer/*"

  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - CADDY_DOMAIN=${DOMAIN}
    networks:
      - portainer-network

networks:
  portainer-network:
    driver: bridge

volumes:
  portainer_data:
  caddy_data:
  caddy_config:
